### ISSUE TITLE
request body

### ISSUE THREAD

**Issue by sean-roberts** [jameslnewell/xhr-mock#1]
currently, req.body() always returns undefined. I think it's a simple adding of 

this.body(xhr.data);

in the MockRequest constructor.

**Comment by sean-roberts** [comment]
Was going to work on a PR but I am not entirely following how your testing is set up

**Comment by jameslnewell** [comment]
Thanks for taking the time to report and submit a PR!

I've merged your PR, added mochify to the `devDep`s and added a  `scripts.test` key to the `package.json`.

**Comment by jameslnewell** [comment]
Published in `1.3.2`.

**Comment by sean-roberts** [comment]
Yep np!
