### ISSUE TITLE
Is not working with mocha

### ISSUE THREAD

**Issue by ayxos** [jameslnewell/xhr-mock#24]
I am doing a sync xhr call with mocha-sinon and i am not able to run it properly. Any idea?

**Comment by jameslnewell** [comment]
Sorry, sync xhr no longer works. See the discussion on here https://github.com/jameslnewell/xhr-mock/pull/23. Let me know if you have any further issues.

**Comment by jameslnewell** [comment]
Note: I think I've changed from sync to async at some stage without making a major version bump. Apologies if that's the case!
