### ISSUE TITLE
Calling timeout function with any arguments throws an exception

### ISSUE THREAD

**Issue by dfedynich** [jameslnewell/xhr-mock#31]
Hello, @jameslnewell . 

## **What's Up**

I want to simulate a time gap to get the response. To achieve this goal I use 
`.timeout(timeout : bool|number)` function according to your spec. However the call of this function with any arguments throws the exception **'timeout of 0ms exceeded'**

## **Example**

```
var mock = require('xhr-mock');
mock.setup();

mock.get(/(api\/users).*/, function(req, res) {
  return res.timeout(1000).status(200).body('<h1>Google</h1>');
});

var axios = require('axios');
axios({url: 'api/users'}).then(
  function(res) {
    console.log('loaded', res.data);
  },
  function(error) {
    console.log('ERROR', error);
  }
);
```

**Comment by jameslnewell** [comment]
Hi @dfedynich. Can you please try `xhr-mock@next` where a timeout looks like `(req, res) => new Promise(() => {});`

**Comment by jameslnewell** [comment]
any luck @dfedynich?
