### ISSUE TITLE
Support XMLHttpRequest.DONE etc.

### ISSUE THREAD

**Issue by michael42** [jameslnewell/xhr-mock#34]
As per [spec](https://xhr.spec.whatwg.org/#interface-xmlhttprequest), the XMLHttpRequest constructor should define the constants UNSENT = 0, OPENED = 1, HEADERS_RECEIVED = 2, LOADING = 3 and DONE = 4. Otherwise, the following snippet doesn't work as intended when using xhr-mock:

````
xhr.onreadystatechange = function () {
  if (xhr.readyState === XMLHttpRequest.DONE) {
    // ...
  }
}
````

**Comment by jameslnewell** [comment]
Hi @michael42. Can you please try `xhr-mock@next` for me. It aligns much closer to the spec.

https://github.com/jameslnewell/xhr-mock/blob/master/src/MockXMLHttpRequest.ts#L37
