### ISSUE TITLE
Release v2

### ISSUE THREAD

**Issue by jameslnewell** [jameslnewell/xhr-mock#37]
👋 Hey ppl using `xhr-mock`. Please let me know when you think v2 is stable enough to release on the masses!

**Comment by gilbarbara** [comment]
I missed this but a changelog would be really helpful.
I'm using the `release` package to generate my GitHub releases and it's a great starting point.

**Comment by jameslnewell** [comment]
Hi @gilbarbara. Releases are a bit manual at the moment but you’ll find the change log here https://github.com/jameslnewell/xhr-mock/blob/master/packages/xhr-mock/CHANGELOG.md

**Comment by gilbarbara** [comment]
Oh, sorry. I just looked at the root for the CHANGELOG. #lerna

**Comment by jameslnewell** [comment]
No worries, I should make it more visible.
