### ISSUE TITLE
Nice Job!

### ISSUE THREAD

**Issue by thebearingedge** [jameslnewell/xhr-mock#4]
Thank you, this module is super useful!

**Comment by jameslnewell** [comment]
Thanks!!!

Let me know (or submit a PR) if the docs can be improved or you need the missing functions implemented.

**Comment by thebearingedge** [comment]
For now it's working well as is. Along with `xhr`, `mocha`, and `jsdom`, testing models/repositories has never been so simple... or fast (ms). :+1: Cheers!
