### ISSUE TITLE
send() only accepts string?

### ISSUE THREAD

**Issue by marcell-calero** [jameslnewell/xhr-mock#53]
Why does an error fire if we put a string in the send ()?
Is not it better to leave the body empty and follow?
Or maybe to put a flag that does not need to put a string

**Comment by jameslnewell** [comment]
Hi Marcell, thanks for raising an issue. `xhr.send()` should accept a string, but one of your mocks may be throwing an error and that triggers `xhr.onerror`. At the moment debugging an error thrown in a handler is quite painful but I'm working on improving the experience in the next version of `xhr-mock`.

If you can provide a working snippet that showcases the error I can help you debug what's going wrong.

**Comment by jameslnewell** [comment]
Closing due to the lack of a response.
