### ISSUE TITLE
Why proxy promise is not exported by default in dist?

### ISSUE THREAD

**Issue by varp** [jameslnewell/xhr-mock#54]

**Comment by varp** [comment]
I'm xhr-mock.js from unpkg.com

**Comment by jameslnewell** [comment]
I’ve een waiting for someone to bring this up 😁

Because I don’t know how to create multiple exports in UMD. Please make a suggestion and we’ll implement it!

**Comment by varp** [comment]
I'll see what can I do 😀Thx

**Comment by jameslnewell** [comment]
Any ideas @varp?

**Comment by varp** [comment]
Nop. I have no time to work on it. As a workaround, I just started to use browserify

**Comment by webextensions** [comment]
To get the browserified version, in folder ```packages/xhr-mock```, execute:
```$ browserify --entry lib/index.js --standalone XHRMock --outfile xhr-mock.browserified.js```
