### ISSUE TITLE
'self' is undefined in MockXMLHttpRequest.prototype.open

### ISSUE THREAD

**Issue by prabhg** [jameslnewell/xhr-mock#6]
In MockXMLHttpRequest.prototype.open function, on following line, 'self' needs to be replaced with 'this'. 
  
  self.readyState = MockXMLHttpRequest.STATE_OPENED;

**Comment by jameslnewell** [comment]
Thanks for reporting!

**Comment by jameslnewell** [comment]
Published in `1.4.1`.
