### ISSUE TITLE
Possible to add a delay?

### ISSUE THREAD

**Issue by idolizesc** [jameslnewell/xhr-mock#61]
I'd like to add a delay to every response (I'm doing some manual testing in the browser and want to simulate how a real server may feel). Is this possible to do? I don't see anything documented.

Thanks!

**Comment by idolizesc** [comment]
FYI I figured out a way, but it's a bit hacky. Would be nice to have proper support built in :)

```ts
mock.get('/url', (_req, _resp) =>
      new Promise((resolve) =>
        delay(DELAY_MS).then(() => {
          const mockResp = new MockResponse();
          mockResp.body(JSON.stringify(mockBody));
          mockResp.status(mockStatus);
          return resolve(mockResp);
        }),
      ),
);
```

**Comment by jameslnewell** [comment]
You could use async/await to simplify your handler:
```js
import delay from 'delay';

mock.get(
  '/url', 
  async (req, res) => {
    await delay(DELAY_MS);
    return res
      .body(JSON.stringify(mockBody))
      .status(mockStatus)
    ;
  }
);
```

What's hacky about it? How would you support it built in?

**Comment by idolizesc** [comment]
Oh, interesting. I didn't realize you could just set the data on the existing `res` -- in that case it's not very hacky.

Maybe just adding some documentation about how Promises are supported and how you could use them for something like this would be cool 👍

**Comment by idolizesc** [comment]
Hmm, when I tried the above I get the following error:

```
xhr-mock: A handler returned an error for the request.

  POST http://localhost/test HTTP/1.1
  accept: application/json, text/plain, */*
  
TypeError: Cannot read property 'status' of null
```

**Comment by jameslnewell** [comment]
Is `mockStatus` undefined? because all the methods on `req/res` have two signatures and `.status(undefined)` means you're returning the status, not the `res` which will be null and won't have a `status` property on it.

**Comment by jameslnewell** [comment]
Care to open a PR for adding a delayed example to the how-to section?

**Comment by idolizesc** [comment]
Sorry, I actually fixed the other issue (hence deleting my comment). It was because the `mockBody` was undefined, so it wasn't doing the setter routine, but rather the getter!

**Comment by idolizesc** [comment]
Sure, I can make a PR for that.
