### ISSUE TITLE
What if I'm expecting an error?

### ISSUE THREAD

**Issue by jonathansp** [jameslnewell/xhr-mock#70]
In my test case I'm expecting an HTTP error, so I mocked XHR response like this:

```javascript
    xhrmock.get('dummy.host/schemas', {
      status: 500,
      reason: 'Internal Server Error',
      body: 'Internal Server Error',
    })

```

How to avoid the follow message to be printed?

```javascript
 PASS  tests/schemas.spec.js
 Console
    console.error node_modules/xhr-mock/lib/MockXMLHttpRequest.js:674
      xhr-mock: No handler returned a response for the request.

        GET dummy.host/schemas HTTP/1.1
```

https://github.com/jameslnewell/xhr-mock/blob/master/packages/xhr-mock/src/MockXMLHttpRequest.ts#L73

**Comment by jameslnewell** [comment]
Hmmm... it shouldn't be showing that message if your mock is registered and your request is being matched e.g. https://codesandbox.io/s/n05m1wl1jl

Can you please check the mock is registered before the request is made and that the request URL matches the mock URL e.g. `dummy.host/schemas` not `http://dummy.host/schemas`

**Comment by jonathansp** [comment]
The mock is registered before the request is done. I've just realized it only happens when I use `jest --watch`.

**Comment by jameslnewell** [comment]
Are you calling `xhrmock.teardown()` after each test? If you already are, can you please provide minimal repository reproducing the problem. Thanks.
