### ISSUE TITLE
Unimplemented error thrown from .responseXML precludes workarounds

### ISSUE THREAD

**Issue by IanDavey** [jameslnewell/xhr-mock#72]
Suppose we have the following in `onreadystatechange`:
```js
let result = this.responseXML || this.responseText || this.response;
```
As `responseXML` is not implemented, xhr-mock outputs the message `This feature hasn't been implmented yet. Please submit an Issue or Pull Request on Github.`

However, in the snippet above we have a workaround, as long as we're not expecting an XML `Document` in our tests.  Rather than just returning `undefined` and making the code under test try `responseText`, the mock just gives up.

**Comment by jameslnewell** [comment]
Makes sense. Looks easy to [implement](https://xhr.spec.whatwg.org/#the-responsexml-attribute). Want to have a crack at it?

**Comment by K0d1Lu** [comment]
I'm facing the same problem, could assign me this issue ?
