### ISSUE TITLE
Option for passthrough on certain requests

### ISSUE THREAD

**Issue by grug** [jameslnewell/xhr-mock#75]
I couldn't see any other issues asking/discussing this, so I'll give it a go:

Does this library have the ability to only mock certain requests and do a passthrough for all non-matching requests? I guess the use case for this is self-explanatory: I have an application I want to mock certain requests for, but not others.

Thanks!

**Comment by jameslnewell** [comment]
Yep! That's what the [`proxy`](https://github.com/jameslnewell/xhr-mock/tree/master/packages/xhr-mock#proxying-requests) is for. Let me know if that doesn't suffice.

**Comment by grug** [comment]
Yep that works perfect!
