### ISSUE TITLE
Add url masks please

### ISSUE THREAD

**Issue by a-x-** [jameslnewell/xhr-mock#89]
As I understand xhr-mock doesn't support express.js-like masks o_O

e.g. /users/:id

**Comment by a-x-** [comment]
you can use [path-to-regexp](https://www.npmjs.com/package/path-to-regexp)

**Comment by jameslnewell** [comment]
Its not released yet but this is supported in `^3`

https://github.com/jameslnewell/xhr-mock/blob/12ab29ba24e41dc24bbe9ac54861a9bc8e177376/packages/router/src/createMiddleware.test.ts#L81
