### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gesa** [jameslnewell/xhr-mock#90]
Since #86 is merged in, do you suppose you could publish a release?
(i'd just `npm i` the commit but i'll be honest i can't figure out how to do that in a monorepo)

**Comment by jameslnewell** [comment]
Thanks for the nudge @gesa. Apologies for the delay, I've been flat out between life and work! Try `xhr-mock@2.5.0`.

**Comment by sidoruk-sv** [comment]
@jameslnewell `2.5.0` was already in the registry (it was published 4 months ago according to https://www.npmjs.com/package/xhr-mock)
Can you bump to `2.5.1`?
